#!/bin/bash
# Launch the Hermes gateway with secrets injected from the headless op-over-cache
# (dotfiles `secrets-run`, cache backend on the Mac mini), then `exec` the real gateway
# so launchd supervises the python process directly (clean signals, no wrapper layer).
#
# This replaces the old path where the gateway self-loaded a plaintext ~/.hermes/.env
# (override=True). The launchd plist (ai.hermes.gateway) points its ProgramArguments here.
# `secrets-run export` fails closed (non-zero) if the cache is missing or a ref is absent,
# so a broken cache stops the gateway loudly instead of starting it credential-less.
#
# NOTE: the plist is generated by `hermes gateway install` — re-running that regenerates
# the plist and drops this wrapper; re-point ProgramArguments here afterwards (or add a
# native launch-wrapper option to hermes). See dotfiles-private headless-secrets rollout.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
SECRETS_RUN="$HOME/.local/bin/secrets-run"
PY="$HERMES_HOME/hermes-agent/venv/bin/python"
TPL="$HERMES_HOME/.env.tpl"

[ -x "$SECRETS_RUN" ] || { echo "gateway-cache-launch: secrets-run not found at $SECRETS_RUN" >&2; exit 1; }
[ -x "$PY" ]          || { echo "gateway-cache-launch: gateway python not found at $PY" >&2; exit 1; }
[ -f "$TPL" ]         || { echo "gateway-cache-launch: env template not found at $TPL" >&2; exit 1; }

# Resolve every op:// ref + literal from the cache into this shell's environment, then
# exec the gateway which inherits them. eval is fed single-quote-safe `export K='V'` lines.
eval "$("$SECRETS_RUN" export --env-file="$TPL")"

exec "$PY" -m hermes_cli.main gateway run --replace
